# 使用正向websocket
# go-cqhttp 服务器地址
host: 'localhost'
# OneBot WebSocket 服务器端口
port: '6700'
# 访问令牌
access_token: ''
# 调试模式
debug: false
# 写日志
write_log: true
# 遇到错误自动重启
auto_reconnect: true
# 选择数据库
select_database: 'mysql'

# 管理员列表
admin:
  - '1000'

# mysql数据库配置
mysql:
  host: 'localhost'
  port: '3306'
  user: 'xwbot'
  password: '123456'
  database: 'xwbot'

# postgresql数据库配置
postgresql:
  host: 'localhost'
  port: '5432'
  user: 'xwbot'
  password: '123456'
  database: 'xwbot'

# sqlite数据库配置
sqlite:
  database: 'xwbot.db3'

# mongodb数据库配置
mongodb:
  uri: 'mongodb://localhost:27017'