# 使用正向 Websocket
# OneBot WebSocket 服务器地址
host: 'localhost'
# OneBot WebSocket 服务器端口
port: '6700'
# 访问令牌
access_token: ''
# 调试模式
debug: false
# 写日志
write_log: true
# 遇到错误自动重启
auto_reconnect: false

# 管理员列表
admin:
  - '1000'

sql: # 数据库配置，多选一
  type: "sqlite3" # 数据库类型，目前支持 sqlite3，mysql，postgres
  sqlite3:
    path: "data.db" # sqlite3 数据库文件路径
    dsn: "" # 数据库 dsn
  mysql:
    host: "127.0.0.1" # 数据库地址
    port: "3306" # 数据库端口
    database: "xwbot" # 数据库名
    username: "xwbot" # 数据库用户名
    password: "123456" # 数据库密码
    dsn: "" # 数据库 dsn
    ssl_mode: "disable" # 数据库连接 ssl 模式
    ca_path: "" # 数据库连接 ca 证书路径
    key_path: "" # 数据库连接 key 证书路径
    cert_path: "" # 数据库连接 cert 证书路径
  postgres:
    host: "127.0.0.1" # 数据库地址
    port: "5432" # 数据库端口
    database: "xwbot" # 数据库名
    username: "xwbot" # 数据库用户名
    password: "123456" # 数据库密码
    dsn: "" # 数据库 dsn
    ssl_mode: "disable" # 数据库连接 ssl 模式
    srv: false # 是否使用 srv 记录连接数据库
    ca_path: "" # 数据库连接 ca 证书路径
    key_path: "" # 数据库连接 key 证书路径
    cert_path: "" # 数据库连接 cert 证书路径