# 使用正向websocket
# go-cqhttp 服务器地址
host: 'localhost'
# go-cqhttp 服务器端口
port: '8080'
# 访问令牌
access_token: ''
# 调试模式
debug: false
# 写日志
write_log: true

# 管理员列表
admin:
  - 1000

# mysql数据库配置
mysql:
  host: 'localhost'
  port: '3306'
  user: ''
  password: ''
  database: ''