name: Build And Push Multi-Arch Docker Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags:
      - 'v*' # 推送符合 v* 模式的标签时触发

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义平台与标签后缀的映射
        include:
          - platform: linux/amd64
            tag_suffix: linux-amd64
          - platform: linux/arm64
            tag_suffix: linux-arm64
          - platform: linux/arm/v7
            tag_suffix: linux-armv7
          - platform: linux/ppc64le
            tag_suffix: linux-ppc64le
          - platform: linux/s390x
            tag_suffix: linux-s390x
          - platform: linux/arm/v5
            tag_suffix: linux-armv5

    steps:
      - uses: actions/checkout@v4

      - name: Determine main tag
        id: main-tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            main_tag="${GITHUB_REF#refs/tags/}"
          else
            main_tag="latest"
          fi
          echo "main_tag=$main_tag" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            network=host

      - name: Build and push (per-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.main-tag.outputs.main_tag }}-${{ matrix.tag_suffix }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  merge-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine main tag
        id: main-tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            main_tag="${GITHUB_REF#refs/tags/}"
          else
            main_tag="latest"
          fi
          echo "main_tag=$main_tag" >> $GITHUB_OUTPUT

      - name: Create multi-arch manifest
        env:
          REPO: ghcr.io/${{ github.repository }}
          MAIN_TAG: ${{ steps.main-tag.outputs.main_tag }}
        run: |
          platforms=(
            "linux/amd64:linux-amd64"
            "linux/arm64:linux-arm64"
            "linux/arm/v7:linux-armv7"
            "linux/ppc64le:linux-ppc64le"
            "linux/s390x:linux-s390x"
            "linux/arm/v5:linux-armv5"
          )

          # 创建 Manifest 列表
          manifest_cmd="docker manifest create $REPO:$MAIN_TAG"
          for pair in "${platforms[@]}"; do
            IFS=':' read -r platform tag_suffix <<< "$pair"
            full_tag="$REPO:$MAIN_TAG-$tag_suffix"

            # 检查镜像是否存在
            if docker manifest inspect $full_tag >/dev/null 2>&1; then
              echo "✅ Adding $platform ($tag_suffix)"
              manifest_cmd+=" --amend $full_tag"
            else
              echo "⚠️  Skipping missing $platform ($tag_suffix)"
            fi
          done

          # 执行创建并推送 Manifest
          eval $manifest_cmd
          docker manifest push $REPO:$MAIN_TAG

          # 如果是 latest 标签，同时更新 latest 的日期标签
          if [[ "$MAIN_TAG" == "latest" ]]; then
            date_tag=$(date -u +"%Y%m%d")
            docker manifest create $REPO:$date_tag $REPO:$MAIN_TAG
            docker manifest push $REPO:$date_tag
          fi