name: Build And Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 定义平台与标签的合法映射
        include:
          - platform: linux/amd64
            tag_suffix: linux-amd64
          - platform: linux/arm64
            tag_suffix: linux-arm64
          - platform: linux/arm/v7
            tag_suffix: linux-armv7
          - platform: linux/ppc64le
            tag_suffix: linux-ppc64le
          - platform: linux/s390x
            tag_suffix: linux-s390x
          - platform: linux/arm/v5
            tag_suffix: linux-armv5

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: Build and push (per-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.tag_suffix }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  merge-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        env:
          REPO: ghcr.io/${{ github.repository }}
        run: |
          # 自动生成架构列表
          platforms=(
            "linux/amd64:linux-amd64"
            "linux/arm64:linux-arm64"
            "linux/arm/v7:linux-armv7"
            "linux/ppc64le:linux-ppc64le"
            "linux/s390x:linux-s390x"
            "linux/arm/v5:linux-armv5"
          )

          # 拉取所有架构镜像并创建 Manifest
          manifest_cmd="docker manifest create $REPO:latest"
          for pair in "${platforms[@]}"; do
            IFS=':' read -r platform tag <<< "$pair"
            full_tag="$REPO:$tag"

            # 检查镜像是否存在
            if docker manifest inspect $full_tag >/dev/null 2>&1; then
              echo "✅ Adding $platform ($tag)"
              manifest_cmd+=" $full_tag"
            else
              echo "⚠️  Skipping missing $platform ($tag)"
            fi
          done

          # 执行 Manifest 创建
          eval $manifest_cmd
          docker manifest push $REPO:latest