name: Build And Push Docker Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: 
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/ppc64le
          - linux/s390x
          - linux/arm/v5

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create builder
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:master

      - name: Build and push (per-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}:${{ matrix.platforms }}
          platforms: ${{ matrix.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  merge-manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        run: |
          docker pull ghcr.io/${{ github.repository }}:linux-amd64
          docker pull ghcr.io/${{ github.repository }}:linux-arm64
          docker pull ghcr.io/${{ github.repository }}:linux-arm-v7
          docker pull ghcr.io/${{ github.repository }}:linux-ppc64le
          docker pull ghcr.io/${{ github.repository }}:linux-s390x
          docker pull ghcr.io/${{ github.repository }}:linux-arm-v5

          docker manifest create ghcr.io/${{ github.repository }}:latest \
            ghcr.io/${{ github.repository }}:linux-amd64 \
            ghcr.io/${{ github.repository }}:linux-arm64 \
            ghcr.io/${{ github.repository }}:linux-arm-v7 \
            ghcr.io/${{ github.repository }}:linux-ppc64le \
            ghcr.io/${{ github.repository }}:linux-s390x \
            ghcr.io/${{ github.repository }}:linux-arm-v5

          docker manifest push ghcr.io/${{ github.repository }}:latest